base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    torch_dtype: auto
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    kvcache:
        method: Naive
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_fake: False
    save_path: /path/to/save/
