base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: model_path
    tokenizer_mode: fast
    torch_dtype: torch.float8_e4m3fn
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 64
        pack_version: gemm_pack
    special:
        trans: True
        trans_version: v2
        weight_clip: True
        save_mem: False
save:
    save_autoawq: True
    save_path: /path/to/save/
