base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: model_path
    tokenizer_mode: fast
    torch_dtype: torch.float8_e4m3fn
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 64
        pack_version: gemm_pack
save:
    save_autoawq: True
    save_path: /path/to/save/
