base:
    seed: &seed 0
model:
    type: Llama
    # Load Quarot-transformed model
    path: /path/to/save_quarot_trans_for_gptq/transformed_model
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: calib data path
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: mse
    act:
        bit: 4
        symmetric: False
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
        online_rotate: True
        fp32_had: True
    quant_out: True
save:
    save_trans: False
    save_fake: False
    save_path: /path/to/save/
