base:
    seed: &seed 42
model:
    type: chat_model_type
    path: model path
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: ultrachat
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    padding: True
    preproc: ultrachat_general
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Awq
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        trans: True
        # The options for "trans_version" include "v1" and "v2".
        trans_version: v2
        weight_clip: True
        clip_sym: True
save:
    save_trans: False
    save_fake: False
    save_path: /path/to/save/
