base:
    seed: &seed 42
model:
    type: Llama
    path: transformed model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: 1
    seq_len: 2048
    preproc: general
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: [wikitext2, c4, ptb]
    download: False
    path: eval data path
    bs: 1
    inference_per_block: False
    # For 70B model eval, bs can be set to 20, and inference_per_block can be set to True.
    # For 7B / 13B model eval, bs can be set to 1, and inference_per_block can be set to False.
    seq_len: 2048
quant:
    method: OmniQuant
    weight:
        bit: 2
        symmetric: False
        granularity: per_group
        group_size: 64
        calib_algo: learnable
        ste: True
    special:
        aug_loss: True
        lwc: True
        let: False
        lwc_lr: 0.01
        let_lr: 0.005
        use_shift: False
        alpha: 0.5
        deactive_amp: True
        epochs: 5
        wd: 0
        search_clip_init: True
        search_scale_init: True
    quant_out: True
save:
    save_trans: False
    save_path: ./save