base:
    seed: &seed 42
model:
    type: model_type
    path: model path
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 512
    bs: 1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: SmoothQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_sgl: True
    save_path: /path/to/save_for_sgl_smooth_w8a8/
